services:
  app:
    build: .
    container_name: paif-backend-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/blogdb
      JWT_SECRET: dev_jwt_secret_key_change_in_production
      FRONTEND_URL: http://localhost:3001
      SEED_TEACHER_EMAIL: professor@paif.com
      SEED_TEACHER_PASSWORD: professor123
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:7
    container_name: paif-backend-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
